---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python3-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: ensure docker is installed
      package:
        name: docker
        state: present
#     - name: start docker
#       service:
#         name: docker
#         state: started
#         enabled: yes
    - name: Ensure we have /etc/docker and manage daemon.json
      block:
        - name: Ensure /etc/docker exists
          file:
            path: /etc/docker
            state: directory
        - name: manage /etc/docker/daemon.json
          template:
            src: docker-daemon.json
            dest: /etc/docker/daemon.json
          notify: restart docker service
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: jenkins
        image: "krish2356/jenkins:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
